name: RunicFilePull
description: Runic Realms File Pull, By Excel
version: 1.0
main: com.runicfilepull.Plugin
#depend: [Plugman, RunicQuests, MythicMobs]
commands:
  filepull:
    description: Pulls files from the RR GitHub
    aliases: [pull, fp]