name: RunicFilePull
description: Runic Realms File Pull, By Excel
version: 1.0
main: com.runicrealms.runicfilepull.Plugin
depend: [RunicQuests, MythicMobs, PlugMan]
commands:
  filepull:
    description: Pulls files from the RR GitHub
    aliases: [pull, fp]