webhook-secret: secret-here
api-token: access-token-here
automatic-sync:
  enabled: true
  port: 25570
config:
  file-path: path-here
  repo:
    path: RunicRealmsGithub/writer-files-config
    branch: main